<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="<?php echo $_layoutParams["route_css"]; ?>/bootstrap.css">
	<link rel="stylesheet" href="<?php echo $_layoutParams["route_css"]?>/bootstrap-theme.min.css">
</head>
<body>
		<div id="container">


			<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo APP_URL?> /pages">Inicio </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Usuarios <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo APP_URL?> /users/add">Agregar</a></li>
            <li><a href="<?php echo APP_URL?> /users">Listado</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="<?php echo APP_URL?> /categories" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categorias <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo APP_URL?>/categories/add">Agregar</a></li>
            <li><a href="<?php echo APP_URL?> /categories">Listado</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Transacciones <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo APP_URL?>/transactions/add">Agregar</a></li>
            <li><a href="<?php echo APP_URL?> /transactions">Listado</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cuentas <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo APP_URL?>/accounts/add">Agregar</a></li>
            <li><a href="<?php echo APP_URL?> /accounts">Listado</a></li>
          </ul>
        </li>
      </ul>
      

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hola <?php echo $_SESSION["username"]; ?> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo APP_URL."/users/logout";?>">Cerrar Sesion</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

			<!--<header>
				<nav>
					<ul>
					<li><a href="<?php echo APP_URL?> /pages">Inicio </a></li>|
					<li><a href="<?php echo APP_URL?> /users">Usuarios </a></li>|
					<li><a href="<?php echo APP_URL?> /types">Tipos de usuarios </a></li>|
					<li><a href="<?php echo APP_URL?> /categories">Categorias </a></li>|
					<li><a href="<?php echo APP_URL?> /accounts">Cuentas </a></li>|
					<li><a href="<?php echo APP_URL?> /transactions">Transacciones </a></li>
				</ul>
			</nav>
			<div class="login">
				Hola <?php echo $_SESSION["username"]; ?>	|
				<a href="<?php echo APP_URL."/users/logout";?>">Salir</a>
			</div>
		</header>-->

	


